/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidarRouteImport } from './routes/validar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelatorioIdRouteImport } from './routes/relatorio.$id'
import { Route as ProcessandoIdRouteImport } from './routes/processando.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicSyncOciRouteImport } from './routes/api/public/sync-oci'
import { Route as ApiPublicIndexKnowledgeRouteImport } from './routes/api/public/index-knowledge'
import { Route as ApiPublicAgentTestRouteImport } from './routes/api/public/agent-test'
import { Route as AuthenticatedAppBaseConhecimentoRouteImport } from './routes/_authenticated/app.base-conhecimento'
import { Route as AuthenticatedAppPodcastAgentIndexRouteImport } from './routes/_authenticated/app.podcast-agent.index'
import { Route as AuthenticatedAppPodcastAgentThreadIdRouteImport } from './routes/_authenticated/app.podcast-agent.$threadId'

const ValidarRoute = ValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioIdRoute = RelatorioIdRouteImport.update({
  id: '/relatorio/$id',
  path: '/relatorio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessandoIdRoute = ProcessandoIdRouteImport.update({
  id: '/processando/$id',
  path: '/processando/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncOciRoute = ApiPublicSyncOciRouteImport.update({
  id: '/api/public/sync-oci',
  path: '/api/public/sync-oci',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIndexKnowledgeRoute = ApiPublicIndexKnowledgeRouteImport.update({
  id: '/api/public/index-knowledge',
  path: '/api/public/index-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentTestRoute = ApiPublicAgentTestRouteImport.update({
  id: '/api/public/agent-test',
  path: '/api/public/agent-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppBaseConhecimentoRoute =
  AuthenticatedAppBaseConhecimentoRouteImport.update({
    id: '/app/base-conhecimento',
    path: '/app/base-conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPodcastAgentIndexRoute =
  AuthenticatedAppPodcastAgentIndexRouteImport.update({
    id: '/app/podcast-agent/',
    path: '/app/podcast-agent/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPodcastAgentThreadIdRoute =
  AuthenticatedAppPodcastAgentThreadIdRouteImport.update({
    id: '/app/podcast-agent/$threadId',
    path: '/app/podcast-agent/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/validar': typeof ValidarRoute
  '/api/chat': typeof ApiChatRoute
  '/processando/$id': typeof ProcessandoIdRoute
  '/relatorio/$id': typeof RelatorioIdRoute
  '/app/base-conhecimento': typeof AuthenticatedAppBaseConhecimentoRoute
  '/api/public/agent-test': typeof ApiPublicAgentTestRoute
  '/api/public/index-knowledge': typeof ApiPublicIndexKnowledgeRoute
  '/api/public/sync-oci': typeof ApiPublicSyncOciRoute
  '/app/podcast-agent/$threadId': typeof AuthenticatedAppPodcastAgentThreadIdRoute
  '/app/podcast-agent/': typeof AuthenticatedAppPodcastAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/validar': typeof ValidarRoute
  '/api/chat': typeof ApiChatRoute
  '/processando/$id': typeof ProcessandoIdRoute
  '/relatorio/$id': typeof RelatorioIdRoute
  '/app/base-conhecimento': typeof AuthenticatedAppBaseConhecimentoRoute
  '/api/public/agent-test': typeof ApiPublicAgentTestRoute
  '/api/public/index-knowledge': typeof ApiPublicIndexKnowledgeRoute
  '/api/public/sync-oci': typeof ApiPublicSyncOciRoute
  '/app/podcast-agent/$threadId': typeof AuthenticatedAppPodcastAgentThreadIdRoute
  '/app/podcast-agent': typeof AuthenticatedAppPodcastAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/validar': typeof ValidarRoute
  '/api/chat': typeof ApiChatRoute
  '/processando/$id': typeof ProcessandoIdRoute
  '/relatorio/$id': typeof RelatorioIdRoute
  '/_authenticated/app/base-conhecimento': typeof AuthenticatedAppBaseConhecimentoRoute
  '/api/public/agent-test': typeof ApiPublicAgentTestRoute
  '/api/public/index-knowledge': typeof ApiPublicIndexKnowledgeRoute
  '/api/public/sync-oci': typeof ApiPublicSyncOciRoute
  '/_authenticated/app/podcast-agent/$threadId': typeof AuthenticatedAppPodcastAgentThreadIdRoute
  '/_authenticated/app/podcast-agent/': typeof AuthenticatedAppPodcastAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/validar'
    | '/api/chat'
    | '/processando/$id'
    | '/relatorio/$id'
    | '/app/base-conhecimento'
    | '/api/public/agent-test'
    | '/api/public/index-knowledge'
    | '/api/public/sync-oci'
    | '/app/podcast-agent/$threadId'
    | '/app/podcast-agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/validar'
    | '/api/chat'
    | '/processando/$id'
    | '/relatorio/$id'
    | '/app/base-conhecimento'
    | '/api/public/agent-test'
    | '/api/public/index-knowledge'
    | '/api/public/sync-oci'
    | '/app/podcast-agent/$threadId'
    | '/app/podcast-agent'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/validar'
    | '/api/chat'
    | '/processando/$id'
    | '/relatorio/$id'
    | '/_authenticated/app/base-conhecimento'
    | '/api/public/agent-test'
    | '/api/public/index-knowledge'
    | '/api/public/sync-oci'
    | '/_authenticated/app/podcast-agent/$threadId'
    | '/_authenticated/app/podcast-agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ValidarRoute: typeof ValidarRoute
  ApiChatRoute: typeof ApiChatRoute
  ProcessandoIdRoute: typeof ProcessandoIdRoute
  RelatorioIdRoute: typeof RelatorioIdRoute
  ApiPublicAgentTestRoute: typeof ApiPublicAgentTestRoute
  ApiPublicIndexKnowledgeRoute: typeof ApiPublicIndexKnowledgeRoute
  ApiPublicSyncOciRoute: typeof ApiPublicSyncOciRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validar': {
      id: '/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof ValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio/$id': {
      id: '/relatorio/$id'
      path: '/relatorio/$id'
      fullPath: '/relatorio/$id'
      preLoaderRoute: typeof RelatorioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processando/$id': {
      id: '/processando/$id'
      path: '/processando/$id'
      fullPath: '/processando/$id'
      preLoaderRoute: typeof ProcessandoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-oci': {
      id: '/api/public/sync-oci'
      path: '/api/public/sync-oci'
      fullPath: '/api/public/sync-oci'
      preLoaderRoute: typeof ApiPublicSyncOciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/index-knowledge': {
      id: '/api/public/index-knowledge'
      path: '/api/public/index-knowledge'
      fullPath: '/api/public/index-knowledge'
      preLoaderRoute: typeof ApiPublicIndexKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-test': {
      id: '/api/public/agent-test'
      path: '/api/public/agent-test'
      fullPath: '/api/public/agent-test'
      preLoaderRoute: typeof ApiPublicAgentTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/base-conhecimento': {
      id: '/_authenticated/app/base-conhecimento'
      path: '/app/base-conhecimento'
      fullPath: '/app/base-conhecimento'
      preLoaderRoute: typeof AuthenticatedAppBaseConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/podcast-agent/': {
      id: '/_authenticated/app/podcast-agent/'
      path: '/app/podcast-agent'
      fullPath: '/app/podcast-agent/'
      preLoaderRoute: typeof AuthenticatedAppPodcastAgentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/podcast-agent/$threadId': {
      id: '/_authenticated/app/podcast-agent/$threadId'
      path: '/app/podcast-agent/$threadId'
      fullPath: '/app/podcast-agent/$threadId'
      preLoaderRoute: typeof AuthenticatedAppPodcastAgentThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppBaseConhecimentoRoute: typeof AuthenticatedAppBaseConhecimentoRoute
  AuthenticatedAppPodcastAgentThreadIdRoute: typeof AuthenticatedAppPodcastAgentThreadIdRoute
  AuthenticatedAppPodcastAgentIndexRoute: typeof AuthenticatedAppPodcastAgentIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppBaseConhecimentoRoute: AuthenticatedAppBaseConhecimentoRoute,
  AuthenticatedAppPodcastAgentThreadIdRoute:
    AuthenticatedAppPodcastAgentThreadIdRoute,
  AuthenticatedAppPodcastAgentIndexRoute:
    AuthenticatedAppPodcastAgentIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ValidarRoute: ValidarRoute,
  ApiChatRoute: ApiChatRoute,
  ProcessandoIdRoute: ProcessandoIdRoute,
  RelatorioIdRoute: RelatorioIdRoute,
  ApiPublicAgentTestRoute: ApiPublicAgentTestRoute,
  ApiPublicIndexKnowledgeRoute: ApiPublicIndexKnowledgeRoute,
  ApiPublicSyncOciRoute: ApiPublicSyncOciRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
